[package]
name = "hiss"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = "4.5.11" 
prettytable-rs = "0.10.0"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
serde_json = "1.0.121"
